# Site
title: 飞翔的猪猪                                          #网站题目
subtitle:                                                #网站子标题
description: 涉及RM、C++、Python、计算机视觉                #描述      
author: Demon                                            #作者 
# Support language: de, en, fr-FR, id, ja, ko, pt-BR, pt, ru, zh-Hans, zh-hk, zh-tw
language: zh-Hans                                        #语言选择    
date_format: '%Y-%m-%d'

# When running the site in a subdirectory (e.g. domain.tld/blog), remove the leading slash (/archives -> archives)
menu: 
  home: /                   #主页图标                      
  categories: /categories/  #种类
  #about: /about/           #关于
  #archives: /archives/     #归档页及其图标
  tags: /tags/              #标签 
  #sitemap: /sitemap.xml    #站点地图
  #commonweal: /404.html    #404  

# 菜单图标
# Icon Mapping:
#   Map a menu item to a specific FontAwesome icon name.
#   Key is the name of menu item and value is the name of FontAwesome icon. Key is case-senstive.
#   When an question mask icon presenting up means that the item has no mapping icon.
menu_icons:
  enable: true
  #KeyMapsToMenuItemKey: NameOfTheIconFromFontAwesome
  home: home
  about: user
  categories: th
  schedule: calendar
  tags: tags
  archives: archive
  sitemap: sitemap
  commonweal: heartbeat

# ---------------------------------------------------------------
# 主题修改，包含三种主题
# ---------------------------------------------------------------
# Schemes
#scheme: Muse
#scheme: Mist
scheme: Pisces
# ---------------------------------------------------------------
#  侧栏设置
# ---------------------------------------------------------------

#显示你的社交链接图标
social:
  GitHub: https://github.com/TongShuo-Demon || github   #github链接
  LinkLabel: Link

social_icons:
  enable: true
  # Icon Mappings.
  # KeyMapsToSocialItemKey: NameOfTheIconFromFontAwesome
  GitHub: github
  Twitter: twitter
  Weibo: weibo

#修改侧边栏头像，images是我新建的文件夹                                    
avatar:  /images/my_photo.jpeg
  
#在侧边栏中是否显示文章标题目录。
toc:
  enable: true
  number: true   #是否自动编号
  wrap: false    # 标题目录是否自动换行

#创作国际4.0声明，开源类的声明
# http://creativecommons.org/
# Available: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
#creative_commons: by-nc-sa
#creative_commons:

sidebar:
  # 侧边栏位置: left | right (只有Pisces、Gemini有效).
  position: left
  #position: right

  # Sidebar Display, available value:
  display: post         # 默认，在post文章扩展时显示。
  #display: always      # 对所有页面都显示
  #display: hide        # 只有点击按钮显示
  #display: remove       # 完全删除，不显示

  # Sidebar offset from top menubar in pixels.
  offset: 12
  offset_float: 0
  b2t: false      # 在侧边栏下方是否显示回到顶部(只对Pisces、Gemini有效).
  scrollpercent: false   #显示百分比

# ---------------------------------------------------------------
# Post Settings 文章设置
# ---------------------------------------------------------------

scroll_to_more: true # 自动折叠<!--more-->下面的正文部分
save_scroll: false   # 自动为每篇文章保存滚动位置
excerpt_description: true #自动摘录首页中的描述作为前导文字。

# 自动摘要 Not recommend.
auto_excerpt: 
  enable: false
  length: 150

# Post meta display settings # 摘要元数据
post_meta:
  item_text: true    # 是否显示“发表于”这几个文字
  created_at: true   # 文章创建日期
  updated_at: false  # 文章修改日期
  categories: true   # 文章所属分类

# Post wordcount display settings
post_wordcount:
  item_text: true      # 是否显示文字
  wordcount: true      # 显示字数
  min2read: false      # 显示阅读时间
  separated_meta: true # 是否分开

# Wechat Subscriber
#wechat_subscriber:    # 微信公众号订阅
  #enabled: true       # 二维码图片链接
  #qcode: /path/to/your/wechatqcode ex. /uploads/wechat-qcode.jpg
  #description: ex. subscribe to my blog by scanning my public wechat account         # 描述性文字，会放在二维码上方

# Declare license on posts 声明版权
post_copyright:             # 文档许可声明
  enable: false
  license: CC BY-NC-SA 3.0  # 文档声明协议  
  license_url: https://creativecommons.org/licenses/by-nc-sa/3.0/

